config/routes.rb
Rails.application.routes.draw do
  resources :line_items, only: [:create] do
    put :remove
    member do
      post :add_cart_item
    end
  end
  resources :carts
  resources :orders, only: [:new, :create]
  resources :musics
  resources :orders_management, only: [:index, :edit] do
    put :confirm_payment
    put :deliver
    member do
      post :async_confirm_payment
      post :async_deliver
    end
  end
  get 'products/index'
  root to: 'products#index'

  devise_for :users
  resources :users
  resources :tags, except: :show
  resources :books do
    resources :taggings, only: [:new, :edit, :create, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < Product
    has_many :taggings
    has_many :tags, through: :taggings
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    
    def add_product(product_id)
        current_item = line_items.find_or_initialize_by(product_id: product_id)
        current_item.quantity += 1
        current_item
    end
    
    def remove_product(line_item_id)
        current_item = line_items.find_or_initialize_by(id: line_item_id)
        current_item.quantity -= 1
        current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
    
    def total_number
        line_items.to_a.sum { |item| item.quantity }
    end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/models/music.rb
class Music < Product
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  enum status: { order_accepted: 0, paid: 1, delivered: 2 }
  belongs_to :user
  has_many :order_details
  after_commit :send_order_mail, on: :create
  
  def checkout(cart)
    cart.line_items.each do |line_item|
      order_details.build(product_id: line_item.product_id, quantity: line_item.quantity)
    end
    save!
  end
  
  def total_price
    order_details.to_a.sum { |item| item.total_price }
  end
  
  def total_number
    order_details.to_a.sum { |item| item.quantity }
  end
  
  aasm column: :status do
    state :order_accepted,initial: true
    state :paid
    state :delivered
    
    event :confirm_payment do
      transitions from: :order_accepted, to: :paid
    end
    
    event :deliver do
      transitions from: :paid, to: :delivered
    end
  end
  
  private
  
  def send_order_mail
    OrderMailer.completed_mail(self).deliver
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_details
    has_many :line_items
    
    scope :books, ->(){ where(type: "Book") }
    scope :musics, ->(){ where(type: "Music") }
    scope :visible, ->(){ where(showing: true) }
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
  has_many :orders
  
  
  ROLE = %w(admin general)
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to products_index_url
      return
    end
    @order = Order.new
    render layout: 'front'
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @cart = current_cart
    @order = Order.new(user_id: order_params[:user_id], shipping_address: order_params[:shipping_address])
    @order.checkout(@cart)

    respond_to do |format|
      @cart.destroy
      session[:cart_id] = nil
      format.html { redirect_to products_index_url, notice: 'Order was successfully created.' }
      format.json { render :show, status: :created, location: @order }
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.html { render :new }
      format.json { render json: @order.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :product_id, :shipping_address)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_url, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_url, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(path_name)
        request.original_fullpath.include?(path_name) ? 'active' : ""
    end
    
    def cart_status_link(cart = nil)
        return if cart.blank?
        count = number_to_currency(cart.try(:total_number), precision: 0, unit: "個")
        price = number_to_currency(cart.try(:total_price), precision: 0, unit: "円")
        link_name = "カート(#{count} #{price})"
        link_to(link_name, cart_path(cart))
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h2 class="sub-header">商品</h2>
  <ul class="list-group">
    <% cart.line_items.each do |line_item| %>
      <li class="list-group-item">
        
        <p>
          <strong>タイトル:</strong>
          <%= line_item.product.title %>
        </p>
        
        <p>
          <strong>個数:</strong>
          <%= number_to_currency(line_item.quantity, precision: 0, unit: "個") %>
        </p>
        
        <p>
          <strong>小計金額:</strong>
          <%= number_to_currency(line_item.total_price, precision: 0, unit: "円") %>
        </p>
        
      </li>
    <% end %>
    <li class="list-group-item">
      
      <p>
        <strong>合計金額:</strong>
        <%= number_to_currency(cart.total_price, precision: 0, unit: "円") %>
      </p>
      
    </li>
  </ul>
  
  <h2 class="sub-header">お客様情報</h2>
  <ul class="list-group">
    <li class="list-group-item">
      
      <p>
        <strong>氏名:</strong>
        <%= current_user.name %>
      </p>
      
    </li>
    
    <li class="list-group-item">
  
      <p>
        <strong>メールアドレス:</strong>
        <%= current_user.email %>
      </p>
      
    </li>

  <div class="form-group">
    <%= f.label :shipping_address %>
    <%= f.text_field :shipping_address, class: "form-control" %>
  </div>
  
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= f.submit '購入確定', class: "btn btn-default", data: { confirm: 'この内容で購入してもよろしいですか？' } %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Shipping address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.shipping_address %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>商品購入</h1>

<%= render 'form', order: @order, cart: @cart %>

<br>

<%= link_to '戻る', products_index_path, class: 'btn btn-default' %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>