config/routes.rb
Rails.application.routes.draw do
  resources :line_items, only: [:create] do
    put :remove
    member do
      post :add_cart_item
    end
  end
  resources :carts
  resources :orders, only: [:new, :create]
  resources :musics
  resources :orders_management, only: [:index, :edit] do
    put :confirm_payment
    put :deliver
    member do
      post :async_confirm_payment
      post :async_deliver
    end
  end
  get 'products/index'
  root to: 'products#index'

  devise_for :users
  resources :users
  resources :tags, except: :show
  resources :books do
    resources :taggings, only: [:new, :edit, :create, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < Product
    has_many :taggings
    has_many :tags, through: :taggings
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    
    def add_product(product_id)
        current_item = line_items.find_or_initialize_by(product_id: product_id)
        current_item.quantity += 1
        current_item
    end
    
    def remove_product(line_item_id)
        current_item = line_items.find_or_initialize_by(id: line_item_id)
        current_item.quantity -= 1
        current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
    
    def total_number
        line_items.to_a.sum { |item| item.quantity }
    end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/models/music.rb
class Music < Product
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  enum status: { order_accepted: 0, paid: 1, delivered: 2 }
  belongs_to :user
  has_many :order_details
  after_commit :send_order_mail, on: :create
  
  def checkout(cart)
    cart.line_items.each do |line_item|
      order_details.build(product_id: line_item.product_id, quantity: line_item.quantity)
    end
    save!
  end
  
  def total_price
    order_details.to_a.sum { |item| item.total_price }
  end
  
  def total_number
    order_details.to_a.sum { |item| item.quantity }
  end
  
  aasm column: :status do
    state :order_accepted,initial: true
    state :paid
    state :delivered
    
    event :confirm_payment do
      transitions from: :order_accepted, to: :paid
    end
    
    event :deliver do
      transitions from: :paid, to: :delivered
    end
  end
  
  private
  
  def send_order_mail
    OrderMailer.completed_mail(self).deliver
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_details
    has_many :line_items
    
    scope :books, ->(){ where(type: "Book") }
    scope :musics, ->(){ where(type: "Music") }
    scope :visible, ->(){ where(showing: true) }
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
  has_many :orders
  
  
  ROLE = %w(admin general)
end

app/controllers/orders_management_controller.rb
class OrdersManagementController < ApplicationController
    before_action :authenticate_user!
    before_action :set_order, only: [:edit, :confirm_payment, :deliver, :async_confirm_payment, :async_deliver]
    
    def async_confirm_payment
        @order.confirm_payment!
        render template: "orders_management/async_process"
    end
    
    def async_deliver
        @order.deliver!
        
        render template: "orders_management/async_process"
    end
    
    def index
        conditions = params[:q] || { status_in: Order.statuses.values }
        @order = Order.ransack(conditions)
        @orders = @order.result.includes(:user).to_a.uniq
    end
    
    def edit
    end
    
    def confirm_payment
        respond_to do |format|
            if @order.confirm_payment!
                format.html { redirect_to orders_management_index_url, notice: 'Order was success fully updated.' }
                format.json { render :index, status: :ok, location: orders_management_index_path}
            else
                format.html { render :edit }
                format.json { render json: @order.errors, status: unprocessable_entity }
            end
        end
    end
    
    def deliver
        respond_to do |format|
            if @order.deliver!
                format.html { redirect_to orders_management_index_url, notice: 'Order was success fully updated.' }
                format.json { render :index, status: :ok, location: orders_management_index_path}
            else
                format.html { render :edit }
                format.json { render json: @order.errors, status: unprocessable_entity }
            end
        end
    end
    
    private
    
    def set_order
        @order = Order.find(params[:id])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/orders_management_helper.rb
module OrdersManagementHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders_management/_form.html.erb
<% if order.errors.any? %>
    <div id="error_explanation">
         <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
        <% order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<h2 class="sub-header">注文内容</h2>

<ul class="list-group">
    <% order.order_details.each do |item| %>
        <li class="list-group-item">
            
            <p>
                <strong>タイトル:</strong>
                <%= item.product.title %>
            </p>
            
            <p>
                <strong>個数:</strong>
                <%= number_to_currency(item.quantity, precision: 0, unit: "個") %>
            </p>

            <p>
                <strong>小計金額:</strong>
                <%= number_to_currency(item.total_price, precision: 0, unit: "円") %>
            </p>
            
        </li>
    <% end %>
    <li class="list-group-item">
        
        <p>
            <strong>合計金額:</strong>
            <%= number_to_currency(order.total_price, precision: 0, unit: "円") %>
        </p>
        
    </li>
    <li class="list-group-item">
        
        <p>
            <strong>氏名:</strong>
            <%= order.user.name %>
        </p>
        
    </li>
    <li class="list-group-item">
        
        <p>
            <strong>メールアドレス:</strong>
            <%= order.user.email %>
        </p>
    
        </li>
    <li class="list-group-item">

        <p>
            <strong>状況:</strong>
            <%= I18n.t order.status, scope: 'activerecord.enum.order.status' %>
        </p>
        
    </li>
</ul>

<% if order.order_accepted? %>
    <%= button_to '入金確認', orders_management_confirm_payment_path(order.id), params: { id: order.id }, method: :put, class: 'btn btn-default' %>
<% elsif order.paid? %>
    <%= button_to '配送', orders_management_deliver_path(order.id), params: { id: order.id }, method: :put, class: 'btn btn-default' %>
<% end %>

app/views/orders_management/async_process.js.erb
var targetStatus = $("#order_table tbody tr#" + "<%= @order.id %>" + " td.status");
var targetLink = $("#order_table tbody tr#" + "<%= @order.id %>" + " td.link");
var link;

$(targetStatus).html("<%= I18n.t @order.status, scope: 'activerecord.enum.order.status' %>");

<% if @order.order_accepted? %>
    link = '<%= link_to "入金確認", async_confirm_payment_orders_management_path(@order), remote: true, method: :post, class: "btn btn-default" %>';
<% elsif @order.paid? %>
    link = '<%= link_to "配送", async_deliver_orders_management_path(@order), remote: true, method: :post, class: "btn btn-default" %>';
<% else %>
    link = '';
<% end %>

$(targetLink).html(link);

app/views/orders_management/edit.html.erb
<h1>注文管理</h1>

<%= render 'form', order: @order %>

<br>

<%= link_to '戻る', orders_management_index_path, class: 'btn btn-default' %>

app/views/orders_management/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<%= javascript_include_tag "orders_management" %>

<h2 class="sub-header">Orders</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">検索</div>
    </div>
    <div class="panel-body">
        <%= search_form_for @order, url: orders_management_index_path do |f| %>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <%= f.label :user_id %>
                        <%= f.search_field :user_name_cont, class: "form-control" %>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <%= f.label :status %>
                        <div class="form-group">
                            <% Order.statuses.each do |key, val| %>
                                <label>
                                    <%= f.check_box :status_in, { multiple: true }, checked_value = val,unchecked_value = "-1" %>
                                    <%= I18n.t key, scope: 'activerecord.enum.order.status' %>
                                </label>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <%= f.submit '検索', class: "btn btn-primary" %>
                </div>
            </div>
        <% end %>
    </div>
</div>


<div class="table-responsive">
    <table id="order_table" class="table table-striped">
        <thead>
            <tr>
                <th>購入者</th>
                <th>送付先</th>
                <th>個数</th>
                <th>金額</th>
                <th>状態</th>
                <th></th>
                <th colspan="2"></th>
            </th>
        </thead>
        <tbody>
            <% @orders.each do |order| %>
                <tr id="<%= order.id %>">
                    <td><%= order.user.name %></td>
                    <td><%= order.shipping_address %></td>
                    <td><%= order.total_number %></td>
                    <td><%= order.total_price %></td>
                    <td class="status">
                        <%= I18n.t order.status, scope: 'activerecord.enum.order.status' %>
                    </td>
                    <td class="link">
                        <% if order.order_accepted? %>
                            <%= link_to '入金確認', "#", onclick: "return async_confirm_payment(this, #{order.id});", class: 'btn btn-default' %>
                        <% elsif order.paid? %>
                            <%= link_to '配送', "#", onclick: "return async_deliver(this, #{order.id});", class: 'btn btn-default' %>
                        <% end %>
                    </td>
                    <td><%= link_to '編集', edit_orders_management_path(order) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>