config/routes.rb
Rails.application.routes.draw do
  resources :line_items, only: [:create] do
    put :remove
    member do
      post :add_cart_item
    end
  end
  resources :carts
  resources :orders, only: [:new, :create]
  resources :musics
  resources :orders_management, only: [:index, :edit] do
    put :confirm_payment
    put :deliver
    member do
      post :async_confirm_payment
      post :async_deliver
    end
  end
  get 'products/index'
  root to: 'products#index'

  devise_for :users
  resources :users
  resources :tags, except: :show
  resources :books do
    resources :taggings, only: [:new, :edit, :create, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < Product
    has_many :taggings
    has_many :tags, through: :taggings
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    
    def add_product(product_id)
        current_item = line_items.find_or_initialize_by(product_id: product_id)
        current_item.quantity += 1
        current_item
    end
    
    def remove_product(line_item_id)
        current_item = line_items.find_or_initialize_by(id: line_item_id)
        current_item.quantity -= 1
        current_item
    end
    
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
    
    def total_number
        line_items.to_a.sum { |item| item.quantity }
    end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/models/music.rb
class Music < Product
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  enum status: { order_accepted: 0, paid: 1, delivered: 2 }
  belongs_to :user
  has_many :order_details
  after_commit :send_order_mail, on: :create
  
  def checkout(cart)
    cart.line_items.each do |line_item|
      order_details.build(product_id: line_item.product_id, quantity: line_item.quantity)
    end
    save!
  end
  
  def total_price
    order_details.to_a.sum { |item| item.total_price }
  end
  
  def total_number
    order_details.to_a.sum { |item| item.quantity }
  end
  
  aasm column: :status do
    state :order_accepted,initial: true
    state :paid
    state :delivered
    
    event :confirm_payment do
      transitions from: :order_accepted, to: :paid
    end
    
    event :deliver do
      transitions from: :paid, to: :delivered
    end
  end
  
  private
  
  def send_order_mail
    OrderMailer.completed_mail(self).deliver
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_details
    has_many :line_items
    
    scope :books, ->(){ where(type: "Book") }
    scope :musics, ->(){ where(type: "Music") }
    scope :visible, ->(){ where(showing: true) }
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
  has_many :orders
  
  
  ROLE = %w(admin general)
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>book</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Monka</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'home', root_path %></li> <!-- ***不要***　-->
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <% if user_signed_in? %>
            <ul class="nav nav-sidebar">
              <li class="<%= active_class('books') %>"><%= link_to 'Books', books_path %></li>
              <li class="<%= active_class('musics') %>"><%= link_to 'Musics', musics_path %></li>
              <li class="<%= active_class('tags') %>"><%= link_to 'Tags', tags_path %></li>
              <li class="<%= active_class('users') %>"><%= link_to 'Users', users_path %></li>
              <li class="<%= active_class('orders') %>"><%= link_to 'Orders', orders_management_index_path %></li>
            </ul>
          <% end %>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

          <%= yield %>

        </div>
      </div>
    </div>

    <script src="bootstrap.min.js"></script>

  </body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monka</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag 'front', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'front', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li id="cart_total_price"><%== cart_status_link(@cart) %></li>
            <li role="presentation" class="active"><a href="/">Home</a></li>
            <li role="presentation" class=""><a href="/users">About</a></li>　<!-- ***defaultは「href="/about"」*** -->
          </ul>
        </nav>
        <h3 class="text-muted">Monka</h3><!-- githubのprj名の公表okかどうか確認が必要です。 -->
      </div>
      
      <% if notice %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <p id="notice"><%= notice %></p>
        </div>
      <% end %>

      <%= javascript_include_tag "line_items" %>
      <div class="jumbotron">
        <h1>F-B Shop</h1>
        <p class="lead">This site is the test shop of my favorite books.</p>
        <p class="lead">Enjoy and select your favorite books!</p>
      </div>

        <%= yield %>

      <footer class="footer">
        <p>&copy; 2016 文科省IT人材育成プロジェクト</p><!-- githubのprj名の公表okかどうか確認が必要です。 -->
        <p>code: </p><!-- 公開するrailsのサンプルコードのURLを書いておきたいです。 -->
      </footer>

    </div> <!-- /container -->

    <script src="bootstrap.min.js"></script>

  </body>
</html>